### PR TITLE
Changed interpolation direction of lerp.

### LINKED ISSUE #164: lerp interpolates the wrong way?
I guess I've never had occasion to use it, but I just noticed that `lerp` (in `Additive`) works the opposite way of any other lerp implementation I've seen. (A brief Googling supports this; see [C++](https://en.cppreference.com/w/cpp/numeric/lerp), [GLSL](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/mix.xhtml), [Unity](https://docs.unity3d.com/ScriptReference/Vector3.Lerp.html), [Processing](https://processing.org/reference/lerp_.html).) I'd expect that

    lerp t a b = a + t * (b - a);

that is, that `lerp 0 a b == a` and `lerp 1 a b == b`, and that is the case in all other implementations. However, the implementation in `linear` is the opposite of this, i.e. `lerp 0 a b == b` and `lerp 1 a b == a`.

Is this mismatch intentional? If so, can it be clearly documented? If not, might it be fixed? I understand that it's longstanding at this point, but maybe something can be done.

### PR DESCRIPTION
**Pull request by gilgamec**
Fixes #164 .

### CODE REVIEW

File: src/Linear/Vector.hs [hunk 1]
```diff
@@ -133,8 +133,13 @@ class Functor f => Additive f where
   x ^-^ y = x ^+^ negated y
 
   -- | Linearly interpolate between two vectors.
+  --
+  -- /Since linear version 1.23, interpolation direction has been reversed; now/
+  --
+  -- prop> lerp 0 a b == a
+  -- prop> lerp 1 a b == b
```
Comment (RyanGlScott) [inline src/Linear/Vector.hs:140]: `cabal-docspec` [doesn't support property tests](https://github.com/phadej/cabal-extras/blob/25bf27f965fbd5722c127112c92189a645c3357a/cabal-docspec/MANUAL.md?plain=1#L595-L598), which means that the CI [skips these two tests entirely](https://github.com/ekmett/linear/actions/runs/8659936783/job/23749282166?pr=178#step:24:66):

```
[   1.02921] warning[-Wskipped-property]: in comment at 135:3 skipping lerp 0 a b == a
[   1.02968] warning[-Wskipped-property]: in comment at 135:3 skipping lerp 1 a b == b
```

Could you move these to the `linear` test suite instead?

**Review by RyanGlScott — COMMENTED** [review]
Thanks, @gilgamec!

File: src/Linear/Vector.hs (hunk 1 above)
Comment (gilgamec) [reply src/Linear/Vector.hs:140]: It looks like the test suite doesn't (currently) support property tests either. I'll just make these code fragments (since they're important for documentation). Unless you want me to add something to the test suite?

Comment (gilgamec) [reply src/Linear/Vector.hs]: I don't really have any experience with QuickCheck, so it'd probably be better for someone else to do it. I don't think this fix should really depend on a test being available, though.

Comment (RyanGlScott) [reply src/Linear/Vector.hs]: I've added some property tests which confirm that `lerp 0` and `lerp 1` behave as advertised. Thanks again for the PR!

**Review by RyanGlScott — APPROVED** [review]
